trigger:
- main 

pool:
  name: my-pc

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'